config/routes.rb
Rails.application.routes.draw do


  get 'requests/create'
  devise_for :users

  root to: 'pages#home'

  resources :dashboards, only: :show  do
    resources :tags, only: [:show, :create, :destroy]
  end
  resources :inboxes, only: [:show, :update]

  resources :videos do
    resources :translations, only: [:new, :create]
    member do
      post "shepherd"
    end
    member do
      post "revoke"
    end
  end

  resources :briefings, only: :index

  resources :translations, except: [:new, :create] do
    member do
      patch "publish"
    end
    member do
      patch "unpublish"
    end
    resources :requests, only: [:create, :destroy, :update]
  end

  resources :formats, only: [:index, :show]

  resources :icons, only: [:index, :show, :new, :create]

  resources :picks, only: [:index, :show, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  has_many :translations, dependent: :destroy

  has_many :videos_tags
  has_many :tags, through: :videos_tags

  belongs_to :shepherd, class_name: "User", optional: true


  validate :url_must_start_with

  def url_must_start_with
    if !video_path.starts_with? 'https://www.youtube.com/embed/'
      errors.add(:video_path, "errorr. The platform currently only supports embedding videos that are hosted on YouTube. To add a video use the 'embed link' provided by YouTube. It can be found under the 'Share' options with any video. Also make sure you set your video to 'unlisted' in the 'setting panel' of YouTube or straight away when uploading. ")
    end
  end


  include PgSearch::Model
      pg_search_scope :search_by_name_and_video_path,
    against: [ :name, :project_path ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }



end

app/controllers/videos_controller.rb
require 'will_paginate/array'
class VideosController < ApplicationController
  def index
    @tags = Tag.all
    @videos = policy_scope(Video)
    if params[:query].present?
      @videos = Video.search_by_name_and_video_path(params[:query])
    elsif params[:tag].present?
      @tag = Tag.where(tag: params[:tag])
      @videos = Video.joins(:tags).where('tags.tag = ?', params[:tag])
    else
      @videos = Video.all
    end
    @videos_sorted = Video.paginate(page: params[:page], per_page: 2)
  end


  def new
    @video = Video.new
    authorize @video
  end

  def create
    @video = Video.new(video_params)
    authorize @video
    @video.user_id = current_user.id
    if @video.save
      redirect_to videos_path
    else
      render :new
    end
  end

  def show
    @icons = Icon.all
    @video = Video.find(params[:id])
    authorize @video
    @edit_translations = @video.translations[1..@video.translations.count-1]

    unless @edit_translations.nil?
      @published_translations = @edit_translations.select do |t|
        t.done == true
      end
      @my_translations = @edit_translations.select {|t| t.user == current_user}
    end
    if current_user.id != @video.user_id
      @video.engagement += 1
      @video.save
    end
  end

  def destroy
   @temp = Video.find(params[:id])
   authorize @temp
   @temp.destroy
   redirect_to inbox_path(current_user.id)
  end


  def shepherd
    @video = Video.find(params[:id])
    authorize @video
    @video.shepherd_id = current_user.id
    @video.save
    redirect_to video_path(@video)
end


def revoke
  @video = Video.find(params[:id])
  authorize @video
  @video.shepherd_id = nil
  @video.save
  redirect_to video_path(@video)
end

  private

  def video_params
    params.require(:video).permit(:video_path, :name, :description)
  end
end

app/views/videos/index.html.erb
<!-- [...] -->

<div class="float-left mt-5 pr-4 pl-4 pt-4">
  <%= form_tag videos_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a video"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>

<div class="mt-5">





<% @tags.each do |tag| %>
  <%= form_tag videos_path, method: :get do %>
    <%= hidden_field_tag :tag, tag.tag%>
    <small><%= submit_tag tag.tag, class: "btn-sm border shadow-sm btn-primary" %></small>
  <% end %>
<% end %>



</div>

</div>

<!-- the list of movies -->


<div class="container pt-5">
<% if !params[:query].blank? %>
  <h4 class="pb-0"> <%= "Search results for: #{params[:query]}" %> </h4>
  <small class=""> <%= link_to "Click here to display all videos", videos_path %> </small>
  <% if @videos.blank? %>
    <h1 class="text-center mt-5 pt-5">No results found <i class="far fa-sad-tear"></i></h1>
  <% else %>
    <h1 class="text-center mt-5 pt-5 pb-5"><%="We found #{@videos.count} result#{@videos.count > 1 ? "s": ""} "%><i class="far fa-smile-wink"></i></h1>
  <% end %>
<% end %>

<h1 class="ml-5 mb-4"><p class="badge badge-secondary pb-2 pt-1"><%=@videos.count%></p><strong> videos to translate:</strong> </h1>
  <div class="row">
    <% @videos.each do |video| %>
      <div class="shadow-sm bg-light pt-2 pb-2 pl-4 m-2" style="width: 29rem;">

          <%= link_to video_path(video) do %>
            <h5 ><%="#{video.name}"%></h5>
            <% end %>

      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="<%=video.video_path%>" allowfullscreen> </iframe>
      </div>

        <% if !video.translations.first %>
          <%= link_to "Awaiting transcript...", video_path(video), class: "btn btn-outline-secondary btn-sm"%>
        <% elsif video.translations.count == 1%>
          <p>Be the first to add a translation</p>
        <% else %>
          <small class="badge badge-primary"><%="#{video.translations.count-1}
          translation#{video.translations.count-1 == 1 ? nil : "s"} available"%></small>
          <% video.tags.each do |tag| %>
          <small class="badge badge-secondary text-white"><%= tag.tag %></small>
          <% end %>
        <% end %>

    </div>
  <% end  %>
  </div>
</div>

<%= will_paginate @videos_sorted, class: "float-right lead btn btn-secondary text-white" %>

app/views/videos/new.html.erb
  <div class="p-2 mb-2 bg-primary text-white">   ⓘ Translations can be linked after adding the video</div>
<div class="container">
  <h1>Add a new video:</h1>

  <%= simple_form_for [@video] do |f| %>
    <%= f.input :name %>
    <%= f.input :video_path %>
    <p class="text-muted">for now you can only provide a youtube embedded url</p>
    <%= f.input :description, value: "blabla"%>

    <%=f.input :campaign?, as: :boolean, checked_value: true, unchecked_value: false %>
    <%= f.submit "add video", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/videos/shephard.html.erb
<h1>hello world</h1>

app/views/videos/show.html.erb
<style>
  #bm {
    height: 20px;
    width: 40px;
    position: relative;
  }


</style>

<!--VIDEO-->
<div class="container">
<div class="row">

    <div class="col-lg-9 col-md-12 shadow-sm p-3  bg-light">

      <h2><%="#{@video.name}"%></h2>
      <div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item" src="<%=@video.video_path%>" allowfullscreen> </iframe>
</div>

          <% @video.tags.each do |tag|  %>
            <span class="badge badge-secondary badge-outlined"><%= tag.tag  %></span>
        <% end %>
        </div>


<!--DESCRIPTION-->

  <div class="col-lg-3 col-md-12  shadow-sm p-2 bg-light">
    <h1>Description:</h1>
      <% if !@video.description.blank? %>
        <p><%="#{@video.description}"%></p>
      <% else %>
        <h2 class="ml-5 far fa-meh-rolling-eyes"></h2>
          <p class="border-bottom pb-2"> No description added</p>
      <% end %>
    <div class="container row">
        <p class="pr-2"> Part of campaign? </p>
        <p><%="#{@video.campaign == true ? "Yes": "No"}"%></p>
      </div>
        <div class="col-lg-12 col-6 bg-light">
      <h5>'Globality' score:</h5>
      <% if  @video.description.blank?%>
      <small>Description missing</small>
      <span id="bm-element-no-loop" class="bm-element-no-loop" data-icon="<%=@icons.where(:name => 'hico-loading-1')[0].json%>"></span>
      <small>Without a description the video is less likely to be found</small>
      <% elsif @video.translations.blank? %>
      <small>Transcript missing</small>
      <span id="bm-element-no-loop" class="bm-element-no-loop" data-icon="<%=@icons.where(:name => 'hico-loading-2')[0].json%>"></span>
      <small>Transcripts provide the base language for others to translate.</small>
      <% elsif @video.shepherd.blank? %>
      <small>No Shepherd yet</small>
      <span id="bm-element-no-loop" class="bm-element-no-loop" data-icon="<%=@icons.where(:name => 'hico-loading-3')[0].json%>"></span>
      <small>When commiting to the role as 'Shepherd' any translation on this piece will be send to you</small>
      <% elsif @video.tags.blank? %>
      <small>Tags are missing</small>
      <span id="bm-element-no-loop" class="bm-element-no-loop" data-icon="<%=@icons.where(:name => 'hico-loading-4')[0].json%>"></span>
      <small>Without tags the video is less likely to be found</small>
      <% else %>
       <small>Content includes all elements</small>
      <span id="bm-element-no-loop" class="bm-element-no-loop" data-icon="<%=@icons.where(:name => 'hico-loading-5')[0].json%>"></span>
      <% end %>
    </div>
  </div>
</div>
</div>

<!--PROVIDE TRANSLATION & REQUEST/SHEPARD-->
<div class=" container shadow bg-light p-5 mb-5">
 <div class="row">
    <% if @video.translations.count == 0%>
      <div class="container">
      <%= link_to "Add Transcript", new_video_translation_path(@video),
      class: "btn btn-outline-secondary"%>
      <span>To make it possible for everyone translate this video,
      we need to start by uploading a base translation in the .JSON format</span>
      </div>
    <% else %>
      <%= link_to "provide a translation", video_translations_path(@video), method: :post,
      class: "btn btn-outline-secondary"%>
    <% if @video.shepherd_id != nil %>
      <div class="dropdown show d-flex">
        <a class="btn btn-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Request video
        </a>
        <% current_user.translations.where(:done => true).each do |translation| %>
          <% if Time.now.utc - translation.updated_at < 0.514022 %>
            <span class="ml-2 mr-2 pt-2"> <i class="fas fa-arrow-left"></i> You can request your video now </span>
        <% end %>
      <% end %>






            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <%  @published_translations.each do |translation| %>
          <!-- max 8 -->
        <%= link_to "#{translation.language}", translation_requests_path(translation), class: "dropdown-item", method: :post%>
        <% if translation == ""  %>
          <p class="dropdown-item">no translations available yet</p>
          <% end %>
    <% end %>
        <% else  %>
          <%= link_to "shepherd production",
          shepherd_video_path,
          class: "btn btn-outline-secondary",
          method: :post%>
      <% end %>



      </div>
<% end %>

<% if @video.shepherd_id == current_user.id%>
<%= link_to "revoke support",
          revoke_video_path,
          class: "btn btn-outline-primary",
          method: :post%>
<% end %>

</div>
</div>
<!--
                                  PUBLISHED TRANSLATIONS:
 -->

<div class="container">
  <h4 clas=> Published translations: </h4>
  <% if @published_translations == [] %>
    <h1 class="ml-5 far fa-meh-rolling-eyes"></h1>
    <p>This video has no published translations</p>
  <% end %>
  <%  @published_translations && @published_translations.each do |translation| %>
  <td>
    <% if current_user.email == translation.user.email %>
    <li><%="language: #{translation.language} | You provided this translation" %></li>
    <% else %>
    <li><%="language: #{translation.language} | Translated by: #{translation.user.email}" %></li>
    <% end %>
  </td>
<% end %>
</div>
</div>
</div>


<!--
                                  YOUR TRANSLATIONS:
 -->

<div class="container shadow bg-light p-5 mb-5 text-primary">
  <h4 id="example"> Your draft translations for: <strong><%=" #{@video.name}"%></strong></h4>
  <% if @video.translations.count > 1 %>
    <% @my_translations.each do |element| %>
      <td>
        <li><%="Language: #{element.language == nil ? "not provided" : element.language}
          | Status: #{element.done ? "published" : "unpublished"}"%></li>
      </td>
      <br>

      <div clas="container">
        <%= link_to "Delete", translation_path(element),
          class: "btn btn-secondary btn-sm",
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
        <%= link_to "edit", edit_translation_path(element),
          class: "btn btn-secondary btn-sm"%>
          <!-- check to see if user provided language before publishing -->
          <%unless element.language == "" %>
            <% if element.done == false %>
              <%= link_to "Publish", publish_translation_path(element), method: :patch,
                class: "btn btn-secondary btn-sm"%>
            <% else %>
              <%= link_to "Unpublish", unpublish_translation_path(element), method: :patch,
                class: "btn btn-secondary btn-sm",
                data: { confirm: "Are you sure you want to unpublish the translation?
                                  This means others users won't be able to see the translation you provided." } %>
            <% end %>
          <% else %>
            <%= link_to "Publish", edit_translation_path(element),
                class: "btn btn-secondary btn-sm",
                data: { confirm: "To pubish please provide a language to your translation." } %>
          <% end %>
          <br>
      </div>
    <% end %>
  <% end %>
  </div>


  <% if @video.translations.first %>
      <%= link_to "Edit transcript",
      edit_translation_path(@video.translations.first.id),
      data: { confirm: "Are you sure? edit transcript influeces every
        translation newly created after the edit to transcript has been made" },
      class: "text-white"%>
  <% else %>
  <p> <%= "no transcript or languages added yet" %> </p>
  <% end %>

  <%  if @video.translations.count > 0%>
  <%= link_to "| Delete transcript", translation_path(@video.translations.first.id),
          class: "text-white",
          method: :delete,
          data: { confirm: "Are you sure?" } %>

    <% end %>
  </div>
</div>