config/routes.rb
Rails.application.routes.draw do


  get 'requests/create'
  devise_for :users

  root to: 'pages#home'

  resources :dashboards, only: :show  do
    resources :tags, only: [:show, :create, :destroy]
  end
  resources :inboxes, only: [:show, :update]

  resources :videos do
    resources :translations, only: [:new, :create]
    member do
      post "shepherd"
    end
    member do
      post "revoke"
    end
  end

  resources :briefings, only: :index

  resources :translations, except: [:new, :create] do
    member do
      patch "publish"
    end
    member do
      patch "unpublish"
    end
    resources :requests, only: [:create, :destroy, :update]
  end

  resources :formats, only: [:index, :show]

  resources :icons, only: [:index, :show, :new, :create]

  resources :picks, only: [:index, :show, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :format
end

app/models/format.rb
class Format < ApplicationRecord
  has_many :scenes
  has_many :choices
  # has_many :icons
end

app/models/icon.rb
class Icon < ApplicationRecord
  has_many :picks

   validate :json_string_must_start_with
   validate :json_string_must_end_with

  def json_string_must_start_with
    if !json.starts_with? '{'
      errors.add(:json, "error. A json string should start with '{'.")
    end
  end

    def json_string_must_end_with
    if !json.ends_with? '}'
      errors.add(:json, "error. A json string should end with '}'.")
    end
  end

end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :translation
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :translation
end

app/models/pick.rb
class Pick < ApplicationRecord
  belongs_to :user
  belongs_to :icon
  # validates :icon, uniqueness: true
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :translation
end

app/models/scene.rb
class Scene < ApplicationRecord
  belongs_to :format
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :videos_tags, dependent: :destroy
  has_many :videos, through: :videos_tags
end

app/models/translation.rb
class Translation < ApplicationRecord
  belongs_to :user
  belongs_to :video
  has_many :lines, dependent: :destroy
  has_many :requests, dependent: :destroy
  accepts_nested_attributes_for :lines




  # validate :qotation_must_be_double


  # def qotation_must_be_double
  #   translation.json.split('').each do |letter|
  #     if letter == "'"
  #       errors.add(:json, "error. A json string should be created with double qotation")
  #     end
  #   end
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :requests
  has_many :videos
  has_many :translations
  has_many :videos_as_shepherd, class_name: 'Video', foreign_key: :shepherd_id
  has_many :picks
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  has_many :translations, dependent: :destroy

  has_many :videos_tags
  has_many :tags, through: :videos_tags

  belongs_to :shepherd, class_name: "User", optional: true


  validate :url_must_start_with

  def url_must_start_with
    if !video_path.starts_with? 'https://www.youtube.com/embed/'
      errors.add(:video_path, "errorr. The platform currently only supports embedding videos that are hosted on YouTube. To add a video use the 'embed link' provided by YouTube. It can be found under the 'Share' options with any video. Also make sure you set your video to 'unlisted' in the 'setting panel' of YouTube or straight away when uploading. ")
    end
  end


  include PgSearch::Model
      pg_search_scope :search_by_name_and_video_path,
    against: [ :name, :project_path ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }



end

app/models/videos_tag.rb
class VideosTag < ApplicationRecord
  belongs_to :tag
  belongs_to :video
end

app/controllers/icons_controller.rb
class IconsController < ApplicationController

  def index
    @icons = Icon.all
    @icons = policy_scope(Icon)
    @picks = Pick.all
  end

  def show
    @icon = Icon.find(params[:id])
    authorize @icon
  end


  def new
    @icon = Icon.new
    authorize @icon
  end


  def create
    @icon = Icon.new(icon_params)
    authorize @icon
    # @icon.user_id = current_user.id
    if @icon.save
      redirect_to icons_path
    else
      render :new
    end
  end

  private

  def icon_params
    params.require(:icon).permit(:json, :name, :hidden)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController

  def create
    @pick = Pick.new
    @pick.user = current_user
    @pick.icon = Icon.find(params[:format])
    authorize @pick
    @pick.save
    redirect_to icons_path
  end

  def destroy
     @pick = Pick.find(params[:id])
     @pick.destroy
     authorize @pick
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @video = Video.find(params[:id])
    authorize @video
    @tags = Tag.all.order('tag ASC')
  end

  def create
    @tag = Tag.find(params[:dashboard_id])
    authorize @tag
    VideosTag.create(video_id: params[:format], tag_id: params[:dashboard_id])
    # temp = Tag.create(:tag => Tag.find(params[:dashboard_id]).tag)
    # x = VideosTags.create(:video_id => params[:format], :tag_id => temp.id)
    redirect_to dashboard_tag_path(params[:dashboard_id] , params[:format])
  end

  def destroy
    @tag = Tag.find(params[:dashboard_id])
    temp = @tag.tag
    authorize @tag
    @tag.destroy
    Tag.create(:tag => temp)
    redirect_to dashboard_tag_path(params[:dashboard_id] , params[:id])
  end
end

app/controllers/videos_controller.rb
require 'will_paginate/array'
class VideosController < ApplicationController
  def index
    @tags = Tag.all
    @videos = policy_scope(Video)
    if params[:query].present?
      @videos = Video.search_by_name_and_video_path(params[:query])
    elsif params[:tag].present?
      @tag = Tag.where(tag: params[:tag])
      @videos = Video.joins(:tags).where('tags.tag = ?', params[:tag])
    else
      @videos = Video.all
    end
    @videos_sorted = Video.paginate(page: params[:page], per_page: 2)
  end


  def new
    @video = Video.new
    authorize @video
  end

  def create
    @video = Video.new(video_params)
    authorize @video
    @video.user_id = current_user.id
    if @video.save
      redirect_to videos_path
    else
      render :new
    end
  end

  def show
    @icons = Icon.all
    @video = Video.find(params[:id])
    authorize @video
    @edit_translations = @video.translations[1..@video.translations.count-1]

    unless @edit_translations.nil?
      @published_translations = @edit_translations.select do |t|
        t.done == true
      end
      @my_translations = @edit_translations.select {|t| t.user == current_user}
    end
    if current_user.id != @video.user_id
      @video.engagement += 1
      @video.save
    end
  end

  def destroy
   @temp = Video.find(params[:id])
   authorize @temp
   @temp.destroy
   redirect_to inbox_path(current_user.id)
  end


  def shepherd
    @video = Video.find(params[:id])
    authorize @video
    @video.shepherd_id = current_user.id
    @video.save
    redirect_to video_path(@video)
end


def revoke
  @video = Video.find(params[:id])
  authorize @video
  @video.shepherd_id = nil
  @video.save
  redirect_to video_path(@video)
end

  private

  def video_params
    params.require(:video).permit(:video_path, :name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CONTENDO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="pl-5 navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to "videos", class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
      <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="pl-5 lead collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <li class="nav-item" id="online">⬤</li>
            <% user = current_user.email %>
            <%= link_to "#{user}", dashboard_path(current_user.id), class: "nav-link" %>
          </li>
          <li class="nav-item active">

          </li>
          <li class="nav-item active">
            <%= link_to "Videos", videos_path, class: "nav-link" %>
          </li>
           <li class="nav-item active">
            <%= link_to "Formats", formats_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Briefings", briefings_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Dashboard", dashboard_path(current_user.id), class: "nav-link", method: :get %>
          </li>
          <li class="nav-item active">
            <%= link_to "Sign-out", destroy_user_session_path, method: :delete,  class: "nav-link"%>
          </li>




          <li class="pt-2 nav-item">
            <%= link_to new_video_path do %>
            <i class="fas fa-cloud-upload-alt text-secondary pl-2"></i>
            <span>Add video</span>
            <% end  %>

          </li>
        <% else %>
            <li class="nav-item" id="offline">⬤</li>
            <li class="nav-link">no user active</li>

          <li>
            <%= link_to "Login", new_user_session_path, class: "btn btn-primary", id: "login-button"%>
          </li>
          <li>
            <%= link_to "< Or sign up here >", new_user_registration_path, class: "nav-link"%>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>