config/routes.rb
Rails.application.routes.draw do


  get 'requests/create'
  devise_for :users

  root to: 'pages#home'

  resources :dashboards, only: :show  do
    resources :tags, only: [:show, :create, :destroy]
  end
  resources :inboxes, only: [:show, :update]

  resources :videos do
    resources :translations, only: [:new, :create]
    member do
      post "shepherd"
    end
    member do
      post "revoke"
    end
  end

  resources :briefings, only: :index

  resources :translations, except: [:new, :create] do
    member do
      patch "publish"
    end
    member do
      patch "unpublish"
    end
    resources :requests, only: [:create, :destroy, :update]
  end

  resources :formats, only: [:index, :show]

  resources :icons, only: [:index, :show, :new, :create]

  resources :picks, only: [:index, :show, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
    rating
    @icons = Icon.all
    @videos = current_user.videos
    @requests = current_user.requests.order(created_at: :desc).where(completed: false)
    @videos_shepherd = User.find(params[:id]).videos_as_shepherd
    authorize @videos
    @jobs = @videos.map do |video|
      video.translations.joins(:requests)
    end.flatten.uniq
    @fulfilled = current_user.requests.order(created_at: :desc).where(completed: true)
  end


    def rating
    total = 0
    total += current_user.videos.count/8.0
    total += current_user.requests.count/8.0
    total += current_user.translations.count/8.0
    @counter = total

    @rating =5

    @stars = ""
    @old_stars = "★★★★★"
      min = 5
        total.round.times do
          @stars += "★"
          min -= 1
          @old_stars = @old_stars[1..min]
        end
      motivating_sentence
    end

    def motivating_sentence
  sentence_one = ["You can do it!", "let's star(t)!"].sample
  sentences = [sentence_one,"First star is close", "Humble beginnings!", "You are almost there!", "Keep 'em coming", "Three stars, perfect", "you are a true contributor", "Four stars, incredible!", "Amazing", "Can I call you master-contributor?"]
  index = @counter*2

  @motivational_sentence = sentences[index]
end

end

app/views/dashboards/show.html.erb
<% 2.times do %>
  <br>
<% end %>




    <div class="shadow mt-5 float-right mr-5 btn btn-light p-2 rounded">
 <p class="lead m-3">Your community <br> score*:</p>
  <div class="ml-2 row">
   <h2 class= "text-secondary"><%= @stars %></h2>
   <h2 class= "text-muted"><%= @old_stars %></h2>
  </div>
  <p><%= @motivational_sentence %></p>
  </div>


<% if @requests.blank? && @videos.blank? && @jobs.blank? %>
  <div class="container">
    <p>Looks like you haven't interacted much with the platform, come back to your personal dashboard once you do.</p>
    <h4 class="far fa-smile"></h4>
  </div>
<% end %>

<% if !@requests.blank? %>
  <div class="container">
    <div class="row">
      <h4 class="p-1">Your requested videos <small class="ml-1 p-1 bg-secondary text-white">where you requested a translation</small></h4>
    </div>
      <table class="table table-hover">
        <thead>
           <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Language</th>
            <th scope="col">Shepherd</th>
            <th scope="col">Status</th>
            <th scope="col">Revoke</th>
           </tr>
        </thead>
        <tbody>
          <% @requests.each_with_index do |request,index| %>
            <% if request.completed == false %>
              <tr>
                <th scope="row"><%= index+1 %></th>
                  <td><%= link_to "#{request.translation.video.name}", video_path(request.translation.video.id), method: :get, class: 'btn-sm btn-light shadow-sm'%>
                    <% if Time.now.utc - request.created_at < 0.114022 %>
                      <small class="btn-sm btn-secondary shadow-sm p-1 text-black"><i class="far fa-arrow-alt-circle-left"></i> recently added</i></small>
                    <% end %>
                  </td>
                    <td><%= request.translation.language%></td>
                    <td><%= request.translation.video.shepherd == nil ? "contact Administrator" : request.translation.video.shepherd.email  %></td>
                    <td>pending</td>
                    <td><%= link_to "revoke", translation_request_path(request.translation.id, request.id),
                    class: "btn-sm btn-success  text-white",
                    method: :delete,
                    data: { confirm: "Are you sure? This request will be revoked from the todo list of the shepherd. You can always re-request a translation" } %></p></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

<% if !@videos.blank? %>
<div class="container">
        <div class="row">
        <h4 class="p-1">Your videos <small class="ml-1 p-1 bg-secondary text-white">what you uploaded</small></h4>
      </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Shepherd</th>
        <th scope="col">Transcript</th>
        <th scope="col">Add tags</th>
        <th scope="col">Views</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>

    <tbody>
  <% @videos.each_with_index do |video,index| %>
      <tr>
        <th scope="row"><%= index+1 %></th>
        <td><%= link_to "#{video.name}", video_path(video.id), method: :get, class: 'btn-sm btn-light shadow-sm'%></td>
          <% if video.shepherd.blank? %>
            <td><%= link_to "claim it", video_path(video.id), method: :get, class: 'btn-sm btn-light shadow-sm'%></td>
          <% elsif video.shepherd.id == current_user.id %>
          <td><%= link_to  "Revoke", inbox_path(video), method: :patch, class: "btn-sm btn-success  text-white"%></td>
          <% end %>
          <td>
              <% if !video.translations.blank? %>
                <%=link_to "Remove transcript", translation_path(video.translations.first.id), class: 'btn-sm btn-light shadow-sm',
                method: :delete,
                data: { confirm: "The video will be removed. Including all user generated translations!" }%>
                <% else %>
                <%= link_to "Add transcript", video_path(video.id), method: :get, class: 'btn-sm btn-light shadow-sm'%></td>
              <% end %>
            </td>
          <td>
            <%= link_to "Click here", dashboard_tag_path(params[:id] ,video), class: "btn-sm btn-success  text-white"%>
          </td>
        <td><%= video.engagement %></td>
        <td>
          <%=link_to "Delete", video_path(video.id), class: 'btn-sm btn-light shadow-sm',
          method: :delete,
          data: { confirm: "The video will be removed. Including all user generated translations!" }%>
        </td>
      </tr>
  <% end %>
    </tbody>
  </table>
</div>
<% end %>

<% if !@jobs.blank? %>
<div class="container">
  <div class="row">
      <h4 class="p-1">Your jobs <small class="ml-1 p-1 bg-secondary text-white">On videos you shepherded</small></h4>
    </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
      </tr>
    </thead>

  <% @jobs.each_with_index do |job,index| %>
    <tbody>
      <tr>
          <th scope="row"><%= index+1 %></th>
          <td><%= link_to "#{job.video.name}", video_path(job.video.id), method: :get, class: 'btn-sm btn-light shadow-sm'%></td>

  </table>
  <table class="table table-hover">
    <thead>
      <th scope="col">Client(s)</th>
      <th scope="col">Status</th>
      <th scope="col">Language</th>
    </thead>

            <% job.requests.each do |request| %>
    <tr>
    <td><%= request.user.email %></td>
    <td>
      <% time = request.created_at %>
      <% if time < 1000000000 %>
      <p>Just added</p>
      <% elsif time > 2000000000 %>
      <p>Priority</p>
      <% elsif time > 5000000000 %>
      <p>Took too long</p>
      <% end %>

    </td>


    <td><%= request.translation.language %></td>
    <td><%= link_to "done", translation_request_path(request.translation.id, request.id),
          class: "btn btn-outline-primary btn-sm",
          method: :delete,
          data: { confirm: "Are you sure? Did you sent the requesting party the video? If not, do that before." } %></td>
    </div>
    </div>
  </tr>
  <% end %>
      </tr>
      <tr>
        <td colspan="5">
          <textarea class="bn-2 bg-dark text-secondary form-control" id="myText" rows="7"><%= job.json %></textarea>
          </td>
        </tr>
    </tbody>
  <% end %>
  </table>
</div>
<% end %>