config/routes.rb
Rails.application.routes.draw do


  get 'requests/create'
  devise_for :users

  root to: 'pages#home'

  resources :dashboards, only: :show  do
    resources :tags, only: [:show, :create, :destroy]
  end
  resources :inboxes, only: [:show, :update]

  resources :videos do
    resources :translations, only: [:new, :create]
    member do
      post "shepherd"
    end
    member do
      post "revoke"
    end
  end

  resources :briefings, only: :index

  resources :translations, except: [:new, :create] do
    member do
      patch "publish"
    end
    member do
      patch "unpublish"
    end
    resources :requests, only: [:create, :destroy, :update]
  end

  resources :formats, only: [:index, :show]

  resources :icons, only: [:index, :show, :new, :create]

  resources :picks, only: [:index, :show, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/icon.rb
class Icon < ApplicationRecord
  has_many :picks

   validate :json_string_must_start_with
   validate :json_string_must_end_with

  def json_string_must_start_with
    if !json.starts_with? '{'
      errors.add(:json, "error. A json string should start with '{'.")
    end
  end

    def json_string_must_end_with
    if !json.ends_with? '}'
      errors.add(:json, "error. A json string should end with '}'.")
    end
  end

end

app/controllers/icons_controller.rb
class IconsController < ApplicationController

  def index
    @icons = Icon.all
    @icons = policy_scope(Icon)
    @picks = Pick.all
  end

  def show
    @icon = Icon.find(params[:id])
    authorize @icon
  end


  def new
    @icon = Icon.new
    authorize @icon
  end


  def create
    @icon = Icon.new(icon_params)
    authorize @icon
    # @icon.user_id = current_user.id
    if @icon.save
      redirect_to icons_path
    else
      render :new
    end
  end

  private

  def icon_params
    params.require(:icon).permit(:json, :name, :hidden)
  end


end

app/views/icons/index.html.erb
<style>
  #bm {
    height: 200px;
    width: 200px;
    position: relative;
  }
</style>


<div class="float-left">
  <div class="ml-5 mr-3 mt-2 shadow" style="width: 16rem;">
    <div class="card-body">
      <h1 class="lead">Your picks:</h1>
      <% @picks.each do |pick| %>
      <li pick_id="<%= pick.id %>">
        <div class=""></div>
        <i class="far fa-trash-alt text-danger"></i>
        <p class="iconToggler"><%= pick.icon.name %></p>
        <div class="d-none">
        <div id="bm" class="bm-element" data-icon="<%=pick.icon.json%>"></div>
        </div>
        <%= link_to "delete", pick, class: "btn-sm btn-primary", method: :delete, remote: true  %>
      </li>
      <% end %>
    </div>
  </div>
</div>

<div class="row pl-5 pt-2">
    <p class="lead">categories:</p>
    <p class="pl-2 lead">cardiovascular</p>
</div>
    <%=link_to "Add icon", new_icon_path, class: "btn btn-primary" %>



<br>
<br>
<br>
<br>

<div class="row ml-5 mt-5 datafetch" >
  <% @icons.where(:hidden => false).each do |icon|%>
      <div class="ml-5 mr-3 mt-2 shadow" style="width: 16rem;">
        <div class="card-body">
          <div id="bm" class="bm-element" data-icon="<%=icon.json%>"></div>
          <h5 class="card-title"><%= icon.name %></h5>
          <a href="#" class="btn-sm btn-primary">More info</a>
          <%= link_to "+", picks_path(icon), class: "btn-sm btn-primary", method: :POST %>
          <%= link_to "show", icon, class: "btn-sm btn-primary", method: :get %>
        </div>
      </div>
    <% end %>
    </div>

app/views/icons/new.html.erb
  <div class="p-2 mb-2 bg-primary text-white">   ⓘ Translations can be linked after adding the video</div>
<div class="container">
  <h1>Add a new video:</h1>

  <%= simple_form_for [@icon] do |f| %>
    <%= f.input :name %>
    <%= f.input :json %>
    <%= f.submit "add video", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/icons/show.html.erb
<style>
  #bm {
    height: 500px;
    width: 500px;
    position: relative;
  }
</style>


  <div class="card">
  <div id="bm" class="bm-element" data-icon="<%=@icon.json%>"></div>
  </div>